[package]
name = "libc-js"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "libcjs"
path = "src/lib.rs"
crate_type = ["dylib"]